language: python
install:
  - pip install coveralls
  - pip install -r requirements.txt
python:
  - "2.7"
  - "3.5"
  - "3.6"
script: nosetests --with-coverage --cover-package=robber tests/
after_success:
  - coveralls
